version: "3.9"

services:
  app:
    build: .
    container_name: medimanage
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - ./:/app
    command: ["mvn", "spring-boot:run"]
  database:
    image: mysql:latest
    container_name: mysql_compose
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pharmacy
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
